export const VERIFY_TOKEN = 'VERIFY_TOKEN';
export const ACTIVATE_TOKEN = 'ACTIVATE_TOKEN';
export const RESET_PASSWORD_TOKEN = 'RESET_PASSWORD_TOKEN';
export const MERCHANT_RESET_PASSWORD_TOKEN = 'MERCHANT_RESET_PASSWORD_TOKEN';

export const ADMIN_RESET_PASSWORD_TOKEN = 'ADMIN_RESET_PASSWORD_TOKEN';
export const USER_LIKE_MERCHANT_CACHE_PREFIX = 'USER_LIKE_MERCHANT';
export const USER_LIKE_STORE_CACHE_PREFIX = 'USER_LIKE_STORE';
export const VERIFY_PHONE = 'VERIFY_PHONE';
export const MERCHANT_ONBOARD = 'MERCHANT_ONBOARD';
export const SYSTEM_META = 'SYSTEM_META';
export const ADMIN_LOGIN = 'ADMIN_LOGIN';

export const OTP = 'OTP';
