version: '3.5'
services:
  redis:
    container_name: nest-be-template-redis
    image: redis:7.0.9
    ports:
      - 6379:6379

  postgres:
    container_name: nest-be-template-postgres
    image: postgres:15.2
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD:-postgres_pw}
      - POSTGRES_USER=${DATABASE_USER_NAME:-postgres_user}
      - POSTGRES_DB=${DATABASE_DB_NAME:-nest_be_template_db}
    volumes:
      - postgres-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8000:8080"

volumes:
  postgres-data:


networks:
  tf-net:
