version: '3.7'

services:
  # Production database (không động vào)
  postgres:
    image: postgres:15
    container_name: postgres_prod
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=production_db
      - POSTGRES_USER=prod_user
      - POSTGRES_PASSWORD=prod_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Test database cho load testing
  postgres_test:
    image: postgres:15
    container_name: postgres_test
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=test_db
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_pass
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
      - ./test-data.sql:/docker-entrypoint-initdb.d/init.sql

  # Redis cache cho testing
  redis_test:
    image: redis:7-alpine
    container_name: redis_test
    ports:
      - "6380:6379"

  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=k6
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin123

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "4000:3000"
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    volumes:
      - ./grafana:/var/lib/grafana

  k6:
    image: grafana/k6:latest
    container_name: k6
    depends_on:
      - influxdb
    entrypoint: ["k6"]
    # ví dụ chạy test k6 (sau bạn có thể override lệnh này)
    command: ["run", "--out", "influxdb=http://influxdb:8086/k6", "/scripts/test.js"]
    volumes:
      - ./scripts:/scripts

volumes:
  postgres_data:
  postgres_test_data: