app:
  version: APP_VERSION
  prefix: APP_PREFIX
  env: APP_ENV
  name: APP_NAME
  port: APP_PORT
  url: APP_URL
  brandName: APP_BRAND_NAME
  brandUrl: APP_BRAND_URL
throttle:
  ttl: THROTTLE_TTL
  limit: THROTTLE_LIMIT
queue:
  job:
    attempts: QUEUE_JOB_ATTEMPTS
    removeOnComplete:
      __name: QUEUE_JOB_REMOVE_ON_COMPLETE
      __format: json
    removeOnFail:
      __name: QUEUE_JOB_REMOVE_ON_FAIL
      __format: json
auth:
  jwt:
    secretKey: AUTH_JWT_SECRET_KEY
    expireTime: AUTH_JWT_EXPIRY
  refreshToken:
    secretKey: AUTH_REFRESH_TOKEN_SECRET_KEY
    expireTime: AUTH_REFRESH_TOKEN_EXPIRY
  verifyToken:
    secretKet: AUTH_VERIFY_TOKEN_SECRET_KEY
    expireTime: AUTH_VERIFY_TOKEN_EXPIRY
logger:
  level: LOGGER_LEVEL
  useFile:
    __name: LOGGER_USE_FILE
    __format: json
redis:
  host: REDIS_HOST
  port: REDIS_PORT
  username: REDIS_USER_NAME
  password: REDIS_PASSWORD
database:
  host: DATABASE_HOST
  port: DATABASE_PORT
  username: DATABASE_USER_NAME
  password: DATABASE_PASSWORD
  database: DATABASE_DB_NAME
pino:
  level: PINO_LOG_LEVEL
  enabled:
    __name: PINO_LOG_ENABLED
    __format: json
  redact:
    enabled:
      __name: PINO_REDACT_ENABLED
      __format: json
    paths:
      __name: PINO_REDACT_PATHS
      __format: json
    censor: PINO_REDACT_CENSOR
smtp:
  host: MAIL_HOST
  port: MAIL_PORT
  username: MAIL_USER_NAME
  password: MAIL_PASSWORD
  secure: MAIL_SECURE
  from: MAIL_FROM