name: CI NestJS

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Show environment info
        run: |
          echo "Node version:"
          node -v
          echo "NPM version:"
          npm -v
          echo "OS:"
          uname -a

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: |
          set -x
          npm ci

      - name: Lint (TSLint)
        run: npx tslint -p tsconfig.json "src/**/*.ts" "src/modules/__tests__/**/*.ts"

      - name: Lint (ESLint)
        run: npm run lint

      - name: Run unit tests
        run: npm run test -- --runInBand --verbose

      - name: Run e2e tests
        run: npm run test:e2e -- --runInBand --verbose

      - name: Build (production)
        if: success()
        run: npm run build
        env:
          NODE_ENV: production

      - name: Upload coverage report
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/

      - name: Upload build artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: |
            dist/
            package-lock.json
            package.json